[package]
name = "bevy_app"
version = "0.1.0"
authors = []
edition = "2018"
repository = "https://github.com/gilescope/dotsamatown"
resolver = "2"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sp-core = "*"

async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
tracing-wasm = "*"
wasm-bindgen = "*"
futures = "0.3.13"
#wasm-bindgen-rayon = "1.0"
#[target.'cfg(target_os = "linux")'.dependencies]

winit = { version = "*", features = ["x11"] }
#sp-keyring = "5.0.0"
bevy_flycam = "0.7"
#bevy_text_mesh = "0.2"
bevy_mod_picking = "0.6"
hex = "*"
#smoldot = { git= "https://github.com/paritytech/smoldot.git", defalult-features = false }
parity-scale-codec = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full", "bit-vec"] }
#bevy_rapier3d = { version = "*", features = [ "simd-nightly", "parallel" ] }
bevy_atmosphere = "0.3"
palette = "0.6"              # why: perceptual color scheme LCH: https://lea.verou.me/2020/04/lch-colors-in-css-what-why-and-how/
fastrand = "*"
bevy-inspector-egui = "0.10"
serde_bytes = "0.11"
#rayon = "*"
serde = "*"
open = "1"
url = "*"
bevy_polyline = "0.2"
lazy_static = "*"
bevy_hanabi = "0.2"
frame-metadata = "*"
scale-info = { version = "*", features = ["serde"] }
desub = { git = "https://github.com/paritytech/desub/" }
desub-current = { git = "https://github.com/paritytech/desub/" }
# Dependencies for native only.
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
bevy = { version = "0.7", default-features = false, features = ["bevy_gltf", "bevy_winit", "render", "png", "dynamic", "jpeg"] }
subxt = { git = "https://github.com/paritytech/subxt.git", rev = "5c04b09c785c1b009ba6a0e18ab6bb5c516d6a71" }


# Dependencies for WASM only.
[target.'cfg(target_arch = "wasm32")'.dependencies]
bevy = { version = "0.7", default-features = false, features = ["bevy_gltf", "bevy_winit", "render", "png", "jpeg"] }
bevy_webgl2 = "*"
getrandom = { version = "*", features = ["wasm-bindgen"] }

# [patch.'https://github.com/bevyengine/bevy']
# bevy = {git = "https://github.com/bevyengine/bevy//", rev="841755aaf23acfd55b375c37390daeb302c5b30b", default-features=false}

# [patch.'https://github.com/mrk-its/bevy_webgl2']
# bevy_webgl2 = {git = "https://github.com/mrk-its/bevy_webgl2//", rev="035236b8d7ec52b8e9e20399662e89c73e4521f6", default-features=false}

#gloo = {version = "0.2.0", optional = true}


#console_error_panic_hook = { version = "0.1", optional = true }

#smoldot = { git= "https://github.com/paritytech/smoldot.git", defalult-features = false }

#subxt = {git= "https://github.com/paritytech/subxt.git"}


#async-std = { version = "1.9.0", features = ["attributes", "tokio1"] }
#sp-keyring = "5.0.0"

# [dependencies.web-sys]
# version = "0.3"
# features = [
#     'console',
#     'Document',
#     'HtmlElement',
#     'HtmlInputElement',
#     'MessageEvent',
#     'Window',
#     'Worker',
# ]

[profile.dev]
opt-level = 1

[profile.release]

[features]
# lto = true
# opt-level = 's'
