name: Release - Create draft

on:
  workflow_dispatch:
    inputs:
      pre_release:
        description: For pre-releases
        default: "true"
        required: true
      ref2:
        description: The 'to' tag to use for the diff
        default: dotsamaworld-v0.1.1
        required: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --locked --verbose --release
    - if: ${{ matrix.os == 'macos-latest' }}
      run: cp target/release/dotsamaworld target/release/dotsamaworld-mac
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: cp target/release/dotsamaworld target/release/dotsamaworld-linux
    - name: Upload lin runtime
      uses: actions/upload-artifact@v3
      with:
        name: dotsamaworld
        path: |
          target/release/dotsamaworld-mac
          target/release/dotsamaworld-linux
          target/release/dotsamaworld.exe
          assets

  publish-draft-release:  
    runs-on: ubuntu-latest
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    needs: build
    steps:
    - uses: actions/download-artifact@v2
    - name: Create draft release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.inputs.ref2 }}
        release_name: ${{ github.event.inputs.ref2 }}
        draft: true