name: Release - Create draft

on:
  push:
    tags:
      - "v*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --locked --verbose --release
    - if: ${{ matrix.os == 'macos-latest' }}
      run: cp target/release/dotsamaworld target/release/dotsamaworld-mac
    - if: ${{ matrix.os == 'ubuntu-latest' }}
      run: cp target/release/dotsamaworld target/release/dotsamaworld-linux
    - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files:  |
            target/release/dotsamaworld-mac
            target/release/dotsamaworld-linux
            target/release/dotsamaworld.exe
            assets