name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-lin:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build-win:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
  build-mac:
    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
