name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - if: ${{ matrix.os == "ubuntu-latest" }}
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Run tests
      run: cargo test --locked --verbose